version: "{build}"
init:
  - git config --global core.autocrlf input
environment:
  matrix:
    - nodejs_version: 0.12
    - nodejs_version: 3
    - nodejs_version: 4
    - nodejs_version: 5
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - cmd: npm test --no-color
build: off
